[bastions]
bastion ansible_host=93.77.191.248

[webservers]
web1 ansible_host=web1.ru-central1.internal
web2 ansible_host=web2.ru-central1.internal

[elasticsearch]
elastic ansible_host=elastic.ru-central1.internal

[monitoring]
zabbix ansible_host=zabbix.ru-central1.internal

[kibana_server]
kibana ansible_host=kibana.ru-central1.internal

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q ubuntu@93.77.191.248"'
